# Name
name		:= Hello
debug		:= 1

# Use packages
libsfx_packages := LZ4

# Derived data files
derived_files	:= Data/SNES.png.palette Data/SNES.png.tiles Data/SNES.png.map
derived_files	+= Data/SNES.png.tiles.lz4 Data/SNES.png.map.lz4

# Include libSFX.make
libsfx_dir	:= ../..
include $(libsfx_dir)/libSFX.make
