# Name
name        := Hello
debug		:= 1

# Derived data files
derived_files := Data/SNES.png.tiles.lz4 Data/SNES.png.tilemap.lz4

# Use packages
libsfx_packages := LZ4

# Include libSFX.make
libsfx_dir	:= ../..
include $(libsfx_dir)/libSFX.make
