# Name
name		:= Tests-Mode21
debug		:= 1

# Derived data files
derived_files := Data/Repetetive.bin.lz4 Data/TheEyesHaveIt.txt.lz4

# Use packages
libsfx_packages := LZ4

# Include libSFX.make
libsfx_dir	:= ../..
include $(libsfx_dir)/libSFX.make
