# Name
name		:= Hello-SMP
debug		:= 1

# Use packages
libsfx_packages	:= SMP_Runtime

# SMP sub-projects
smp_overlays := SMP

# Include libSFX.make
libsfx_dir	:= ../..
include $(libsfx_dir)/libSFX.make
