# Name
name		:= SixteenMegaPower
debug		:= 1

# Stack space allocated from $2000 and downwards
stack_size	:= 200

# Set custom dir for intermediate build files
obj_dir		:= _build_

# Include libSFX.make
libsfx_dir	:= ../..
include $(libsfx_dir)/libSFX.make
