# Name
name		:= SixteenMegaPower
debug		:= 1

# Stack space allocated from $2000 and downwards
stack_size	:= 200
# Zeropage space reserved from $0000 and upwards which will not be allocated by ZEROPAGE BSS segments
zpad_size	:= 30

# Set custom dir for intermediate build files
obj_dir		:= _build_

# Include libSFX
libsfx_dir	:= ../../libSFX
include $(libsfx_dir)/libSFX.make
